name: Next.js CI

on:
  push:
    paths:
      - 'nextjs/**'
  pull_request:
    paths:
      - 'nextjs/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install
      working-directory: ./nextjs

    - name: Run lint
      run: npm run lint
      working-directory: ./nextjs

    - name: Run build
      run: npm run build
      working-directory: ./nextjs

    - name: Run tests
      run: npm test
      working-directory: ./nextjs
